# Generated by Django 5.1 on 2024-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_remove_surflesson_surf_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
