# Generated by Django 5.1 on 2024-08-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_equipment_is_rent_equipment_is_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surflesson',
            name='surfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='AppWeb.surfer'),
        ),
    ]
