# Generated by Django 5.1 on 2024-08-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_alter_surflesson_surfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
