# Generated by Django 5.1 on 2024-08-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_forum_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
