# Generated by Django 5.1 on 2024-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0009_photo_delete_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfer',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
