# Generated by Django 5.1 on 2024-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0011_alter_surfer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfer',
            name='photo',
            field=models.ImageField(null=True, upload_to='surfers_photo/'),
        ),
    ]
