# Generated by Django 5.1 on 2024-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0012_alter_surfer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfclub',
            name='logo',
            field=models.ImageField(null=True, upload_to='surfclubs_logo/'),
        ),
    ]
