# Generated by Django 5.1 on 2024-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0013_alter_surfclub_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfclub',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
