# Generated by Django 5.1 on 2024-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0014_alter_surfclub_logo_alter_surfer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
