# Generated by Django 5.1 on 2024-08-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0017_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surf_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='AppWeb.surfclub'),
            preserve_default=False,
        ),
    ]
