# Generated by Django 5.1 on 2024-08-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0018_order_surf_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='surf_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_club', to='AppWeb.surfclub'),
        ),
    ]
