# Generated by Django 5.1 on 2024-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0019_alter_order_surf_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
